### ISSUE TITLE
Some globbing cases fail on Windows

### ISSUE THREAD

**Issue by hravnx** [seanamos/FsMake#46]
Using FsMake 0.4, the following clean step fails when run on Windows.

```fsharp
let clean = Step.create "clean" {
    Glob.create "**/bin"
    |> Glob.add "**/obj"
    |> Glob.toPaths
    |> Seq.iter (fun x -> Directory.Delete(x, true))
}
``` 

Running the above step in a project rooted at `C:\src\repo` gives the following error:
> System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\\src\\repo\\**'

Note that this also happens if running the clean step via FsMake build.fsx itself. For example, setting `CLEAN=1` and 
running the tests with 

> dotnet fsi .\build.fsx test

gives the same error.

Note also that running `dotnet run --project FsMake.Tests` in the FsMake root folder has a number of unit tests failing in `Unit/Glob.fs`, so I suspect there is something in the globbing logic that doesn't work when `Path.DirectorySeparatorChar` is a backslash.

**Comment by seanamos** [comment]
Thanks for the report.

This is probably as a result of me testing exclusively on Mac/Linux. I'll blow the dust off my Windows setup and get to the bottom of this.

**Comment by hravnx** [comment]
Cool, thanks :-) If you need me to test something, let me know. 

You may know this already, but MS already maintains a library for globbing [here](https://www.nuget.org/packages/Microsoft.Extensions.FileSystemGlobbing)

Maybe that can save you handling some corner cases.

**Comment by seanamos** [comment]
@hravnx If you could try again with version `0.5.0-beta.2`.

I'm aware of `Microsoft.Extensions.Globbing`. For the time being I want to try avoid dependencies, but will re-asses if the globbing code/cases gets too hairy.
