### ISSUE TITLE
How to signal step Failures

### ISSUE THREAD

**Issue by AngelMunoz** [seanamos/FsMake#81]
Hey there!

Another question, how do you signal when a step failed?

For the moment I have code like this

```fsharp
let plwScriptPath (ctx: MakeContext) =
    let result =
        Cmd.createWithArgs "dotnet" [ "--version" ]
        |> Cmd.redirectOutput Cmd.Redirect
        |> Cmd.result

    result ctx
    |> Result.bind (fun result -> parseOutput result.Output.Std)
    |> Result.map (fun version ->
        let dir = if isRelease then "Release" else "Debug"
        let version = $"net%i{version}.0"
        //bin\Debug\net6.0\playwright.ps1
        Path.Combine("./", "bin", dir, version, "playwright.ps1"))

let plwInstall =
    Step.create "playwright-install" {
        let! ctx = Step.context

        match plwScriptPath ctx with
        | Ok path -> do! Cmd.createWithArgs "pwsh" [ path; "install" ] |> Cmd.run
        | Error msg -> failwith "%A" msg
    }
```

As you can see I use the `Result<'a, 'b>` type to run some sort of sub-command (which I'm not sure if there's support for that as well) in any case, when I'm done with the sub-command if I have an error I just use a `failwith` but I'm not sure if there's a way to `return` an Error or something like that.

Also, does the sub-command make sense? I initially wanted to "pass" the result of a Step into the next step, but I don't think that's supported so I preferred to code it like that not sure if that's something worth of its own feature

**Comment by seanamos** [comment]
There are a couple ways you can signal an error from a `Step` that FsMake will handle.

The simplest is just throwing an exception. FsMake will handle the exception, report the step to have failed and write the exception and stacktrace to the console.

Other ways are with the `Make.fail` / `Step.fail` functions:

```fsharp
let thisFails : Make<unit> =
    make {
        do! Make.fail "Boom!"
    }

let thisCanFail (shouldFail: bool) : Make<string> =
    make {
        if shouldFail then
            return! Make.fail "Boom!"
        else
            return "Success!"
    }

let step = Step.create "fails" {
    do! thisFails // fails step
    let! result1 = thisCanFail true // fails step
    let! result2 = thisCanFail false // success
    do! Step.fail "Boom!" // fails step
}
```

You can also work directly with the types if you want to:

```fsharp
let example (shouldFail: bool) : Make<string> =
    fun (ctx: MakeContext) ->
        if shouldFail then
            [Console.error "Boom!"]
            |> MakeError
            |> Error
        else
            Ok "Success"

let step = Step.create "fails" {
    let! test = example true // error
    ()
}
```

**Comment by AngelMunoz** [comment]
I see that helps quite a bit and thank you for your answers on both issues

I might come back to ask more questions but for the moment I think this also helps with what I had in mind
